[package]
name = "pi-metrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
libsql-client = "0.33.4"
url = "2.5.0"
tokio = { version = "1", features = ["full"] }
